[build-system]
requires = ["maturin>=1.8,<2"]
build-backend = "maturin"

[project]
name = "eventcv"
version = "0.0.1"
description = "Open source event-based computer vision library."
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [
  { name = "Adam Hines", email = "a.david.hines@gmail.com"}
]
dependencies = [
    "numpy>=1.24"
]

[tool.maturin]
bindings = "pyo3"
manifest-path = "crates/eventcv-py/Cargo.toml"
python-source = "python"
module-name = "eventcv._rust"