"""Functional (OpenCV-style) call API — §D1.

Every stream/frame op is also a module-level free function taking the object as its
first argument (``ecv.flip_x(stream)`` mirrors ``stream.flip_x()``). These forwarders
are auto-generated by introspecting the Rust methods, so the test asserts the two forms
are identical across a representative op of each kind and that the names are exported.
"""

import inspect
import unittest
from pathlib import Path

import numpy as np

import eventcv

EXAMPLE_NPZ = Path(__file__).resolve().parent.parent / "data" / "test" / "example.npz"


class TestFunctionalApi(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.stream = eventcv.load(str(EXAMPLE_NPZ))

    def test_transform_free_function_matches_method(self):
        s = self.stream
        np.testing.assert_array_equal(eventcv.flip_x(s).numpy(), s.flip_x().numpy())
        np.testing.assert_array_equal(
            eventcv.crop(s, 0, 0, 100, 100).numpy(), s.crop(0, 0, 100, 100).numpy()
        )

    def test_filter_free_function_matches_method(self):
        s = self.stream
        np.testing.assert_array_equal(
            eventcv.hot_pixel_filter(s).numpy(), s.hot_pixel_filter().numpy()
        )

    def test_representation_free_function_matches_method(self):
        s = self.stream
        np.testing.assert_array_equal(eventcv.voxel(s, bins=5).numpy(), s.voxel(bins=5).numpy())
        np.testing.assert_array_equal(eventcv.count(s).numpy(), s.count().numpy())

    def test_free_function_chaining(self):
        s = self.stream
        np.testing.assert_array_equal(
            eventcv.voxel(eventcv.flip_x(s), bins=3).numpy(),
            s.flip_x().voxel(bins=3).numpy(),
        )

    def test_forwarder_dispatches_on_frame(self):
        frame = self.stream.count()
        np.testing.assert_array_equal(eventcv.numpy(frame), frame.numpy())

    def test_ops_are_listed_and_documented(self):
        for name in ("flip_x", "hot_pixel_filter", "voxel", "connected_components"):
            self.assertIn(name, eventcv.__all__)
            self.assertIn(name, dir(eventcv))
            self.assertTrue(getattr(eventcv, name).__doc__)

    def test_curated_functions_not_clobbered(self):
        # `save` is a method too, but the curated dispatch (with `topic=`) must win.
        self.assertIn("topic", inspect.signature(eventcv.save).parameters)


if __name__ == "__main__":
    unittest.main()
